export const generatedModuleConfigs = {
  "fileupload": {
    label: "Authentication - FileUpload",
    module: "FileUpload",
    idField: "FileUpload_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "auth-register": {
    label: "Authentication - Auth Register",
    module: "Auth/Register",
    idField: "Auth_Register_id",
    fields: [
      { name: "full_name", label: "Full Name" },
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "mobile_number", label: "Mobile Number" },
      { name: "profile_url", label: "Profile Url", type: "image" },
      { name: "password", label: "Password", type: "password" },
    ],
    listFields: ["full_name", "email_id", "mobile_number", "profile_url", "password"],
  },
  "auth-password-login": {
    label: "Authentication - Auth Password Login",
    module: "Auth/Password-Login",
    idField: "Auth_Password-Login_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "password", label: "Password", type: "password" },
    ],
    listFields: ["email_id", "password"],
  },
  "auth-otp-login": {
    label: "Authentication - Auth OTP Login",
    module: "Auth/OTP-Login",
    idField: "Auth_OTP-Login_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
    ],
    listFields: ["email_id"],
  },
  "auth-verify-login-otp": {
    label: "Authentication - Auth Verify Login OTP",
    module: "Auth/Verify-Login-OTP",
    idField: "Auth_Verify-Login-OTP_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "otp", label: "Otp" },
    ],
    listFields: ["email_id", "otp"],
  },
  "auth-reset-password": {
    label: "Authentication - Auth Reset Password",
    module: "Auth/Reset-Password",
    idField: "Auth_Reset-Password_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "old_password", label: "Old Password", type: "password" },
      { name: "new_password", label: "New Password", type: "password" },
    ],
    listFields: ["email_id", "old_password", "new_password"],
  },
  "auth-forgot-password": {
    label: "Authentication - Auth Forgot Password",
    module: "Auth/Forgot-Password",
    idField: "Auth_Forgot-Password_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
    ],
    listFields: ["email_id"],
  },
  "auth-forgot-password-confirm": {
    label: "Authentication - Auth Forgot Password Confirm",
    module: "Auth/Forgot-Password-Confirm",
    idField: "Auth_Forgot-Password-Confirm_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "transaction_id", label: "Transaction Id" },
      { name: "new_password", label: "New Password", type: "password" },
    ],
    listFields: ["email_id", "transaction_id", "new_password"],
  },
  "mail-send-mail": {
    label: "Mail - Mail Send Mail",
    module: "Mail/Send-Mail",
    idField: "Mail_Send-Mail_id",
    fields: [
      { name: "to", label: "To" },
      { name: "subject", label: "Subject" },
      { name: "html", label: "Html" },
      { name: "text", label: "Text" },
    ],
    listFields: ["to", "subject", "html", "text"],
  },
  "mail-send-otp-email": {
    label: "Mail - Mail Send OTP Email",
    module: "Mail/Send-OTP-Email",
    idField: "Mail_Send-OTP-Email_id",
    fields: [
      { name: "email_id", label: "Email Id", type: "email" },
    ],
    listFields: ["email_id"],
  },
  "user-roles": {
    label: "User - Roles - User Roles",
    module: "User-Roles",
    idField: "User-Role_id",
    fields: [
      { name: "user_id", label: "User Id" },
      { name: "role_id", label: "Role Id" },
      { name: "assigned_at", label: "Assigned At", type: "date" },
      { name: "isactive", label: "Isactive", type: "checkbox" },
      { name: "isdeleted", label: "Isdeleted" },
      { name: "full_name", label: "Full Name" },
      { name: "email_id", label: "Email Id", type: "email" },
      { name: "role_name", label: "Role Name" },
      { name: "role_code", label: "Role Code" },
    ],
    listFields: ["user_id", "role_id", "assigned_at", "isactive", "isdeleted"],
  },
  "user-roles-user": {
    label: "User - Roles - User Roles User",
    module: "User-Roles/User",
    idField: "User-Roles_user_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "user-roles-add": {
    label: "User - Roles - User Roles Add",
    module: "User-Roles/Add",
    idField: "User-Roles_add_id",
    fields: [
      { name: "user_id", label: "User Id" },
      { name: "role_id", label: "Role Id" },
    ],
    listFields: ["user_id", "role_id"],
  },
  "user-roles-remove": {
    label: "User - Roles - User Roles Remove",
    module: "User-Roles/Remove",
    idField: "User-Roles_remove_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "addresses": {
    label: "Addresses",
    module: "Addresses",
    idField: "Addresse_id",
    fields: [
      { name: "user_id", label: "User Id" },
      { name: "full_name", label: "Full Name" },
      { name: "mobile_number", label: "Mobile Number" },
      { name: "house_street", label: "House Street" },
      { name: "city", label: "City" },
      { name: "state", label: "State" },
      { name: "pincode", label: "Pincode" },
      { name: "emailid", label: "Emailid", type: "email" },
    ],
    listFields: ["user_id", "full_name", "mobile_number", "house_street", "city"],
  },
  "menu-category": {
    label: "Menu Category",
    module: "Menu-Category",
    idField: "Menu-Category_id",
    fields: [
      { name: "menu_category_name", label: "Menu Category Name" },
      { name: "menu_category_slug", label: "Menu Category Slug" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["menu_category_name", "menu_category_slug", "display_order"],
  },
  "menu-sub-category": {
    label: "Menu Sub Categories - Menu Sub Category",
    module: "Menu-Sub-Category",
    idField: "Menu-Sub-Category_id",
    fields: [
      { name: "menu_category_id", label: "Menu Category Id" },
      { name: "menu_subcategory_name", label: "Menu Subcategory Name" },
      { name: "menu_subcategory_slug", label: "Menu Subcategory Slug" },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["menu_category_id", "menu_subcategory_name", "menu_subcategory_slug", "redirect_link", "display_order"],
  },
  "products-media": {
    label: "Products-Media - Products Media",
    module: "Products-Media",
    idField: "Products-Media_id",
    fields: [
      { name: "product_id", label: "Product Id" },
      { name: "product_variant_id", label: "Product Variant Id" },
      { name: "media_type", label: "Media Type" },
      { name: "media_url", label: "Media Url", type: "image" },
      { name: "alt_text", label: "Alt Text" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isprimary", label: "Isprimary" },
    ],
    listFields: ["product_id", "product_variant_id", "media_type", "media_url", "alt_text"],
  },
  "products-seo": {
    label: "Products-Seo - Products Seo",
    module: "Products-Seo",
    idField: "Products-Seo_id",
    fields: [
      { name: "product_id", label: "Product Id" },
      { name: "seo_title", label: "Seo Title" },
      { name: "seo_description", label: "Seo Description", type: "textarea" },
      { name: "seo_keywords", label: "Seo Keywords" },
      { name: "og_image_url", label: "Og Image Url", type: "image" },
    ],
    listFields: ["product_id", "seo_title", "seo_description", "seo_keywords", "og_image_url"],
  },
  "products-cloth-type-care-instructions": {
    label: "Products-Cloth-Type-Care-Instructions - Products Cloth Type Care Instructions",
    module: "Products-Cloth-Type-Care-Instructions",
    idField: "Products-Cloth-Type-Care-Instruction_id",
    fields: [
      { name: "cloth_type_id", label: "Cloth Type Id" },
      { name: "care_instruction_id", label: "Care Instruction Id" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["cloth_type_id", "care_instruction_id", "display_order"],
  },
  "products-care-instructions": {
    label: "Products-Care-Instructions - Products Care Instructions",
    module: "Products-Care-Instructions",
    idField: "Products-Care-Instruction_id",
    fields: [
      { name: "instruction_text", label: "Instruction Text" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["instruction_text", "display_order"],
  },
  "products-cloth-types": {
    label: "Products-Cloth-Types - Products Cloth Types",
    module: "Products-Cloth-Types",
    idField: "Products-Cloth-Type_id",
    fields: [
      { name: "cloth_type_name", label: "Cloth Type Name" },
      { name: "cloth_type_slug", label: "Cloth Type Slug" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["cloth_type_name", "cloth_type_slug", "description", "display_order"],
  },
  "products-sizes": {
    label: "Products-Sizes - Products Sizes",
    module: "Products-Sizes",
    idField: "Products-Size_id",
    fields: [
      { name: "size_name", label: "Size Name" },
      { name: "size_type", label: "Size Type" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["size_name", "size_type", "display_order"],
  },
  "products-attributes-values": {
    label: "Products-Attributes-Values - Products Attributes Values",
    module: "Products-Attributes-Values",
    idField: "Products-Attributes-Value_id",
    fields: [
      { name: "product_id", label: "Product Id" },
      { name: "product_variant_id", label: "Product Variant Id" },
      { name: "attribute_id", label: "Attribute Id" },
      { name: "attribute_value", label: "Attribute Value" },
    ],
    listFields: ["product_id", "product_variant_id", "attribute_id", "attribute_value"],
  },
  "products-attributes": {
    label: "Products-Attributes - Products Attributes",
    module: "Products-Attributes",
    idField: "Products-Attribute_id",
    fields: [
      { name: "attribute_name", label: "Attribute Name" },
      { name: "attribute_slug", label: "Attribute Slug" },
      { name: "attribute_type", label: "Attribute Type" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["attribute_name", "attribute_slug", "attribute_type", "display_order"],
  },
  "products-variants": {
    label: "Products-Variants - Products Variants",
    module: "Products-Variants",
    idField: "Products-Variant_id",
    fields: [
      { name: "product_id", label: "Product Id" },
      { name: "sku", label: "Sku" },
      { name: "variant_name", label: "Variant Name" },
      { name: "price", label: "Price", type: "number" },
      { name: "stock_qty", label: "Stock Qty", type: "number" },
      { name: "size_id", label: "Size Id" },
      { name: "cloth_type_id", label: "Cloth Type Id" },
      { name: "isdefault", label: "Isdefault" },
    ],
    listFields: ["product_id", "sku", "variant_name", "price", "stock_qty"],
  },
  "appointment-date-slots": {
    label: "Appointment-Date-Slots - Appointment Date Slots",
    module: "Appointment-Date-Slots",
    idField: "Appointment-Date-Slot_id",
    fields: [
      { name: "slot_date", label: "Slot Date", type: "date" },
      { name: "slot_duration_minutes", label: "Slot Duration Minutes", type: "number" },
      { name: "isavailable", label: "Isavailable", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    listFields: ["slot_date", "slot_duration_minutes", "isavailable", "notes"],
  },
  "appointment-slot-blocks": {
    label: "Appointment-Slot-Blocks - Appointment Slot Blocks",
    module: "Appointment-Slot-Blocks",
    idField: "Appointment-Slot-Block_id",
    fields: [
      { name: "appointment_date_slot_id", label: "Appointment Date Slot Id" },
      { name: "block_start_time", label: "Block Start Time" },
      { name: "block_end_time", label: "Block End Time" },
      { name: "block_reason", label: "Block Reason" },
      { name: "blocked_by", label: "Blocked By" },
    ],
    listFields: ["appointment_date_slot_id", "block_start_time", "block_end_time", "block_reason", "blocked_by"],
  },
  "appointment-time-slots": {
    label: "Appointment-Time-Slots - Appointment Time Slots",
    module: "Appointment-Time-Slots",
    idField: "Appointment-Time-Slot_id",
    fields: [
      { name: "appointment_date_slot_id", label: "Appointment Date Slot Id" },
      { name: "slot_start_time", label: "Slot Start Time" },
      { name: "slot_end_time", label: "Slot End Time" },
      { name: "isavailable", label: "Isavailable", type: "number" },
      { name: "isbooked", label: "Isbooked", type: "number" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    listFields: ["appointment_date_slot_id", "slot_start_time", "slot_end_time", "isavailable", "isbooked"],
  },
  "custom-appointments": {
    label: "Custom-Appointments - Custom Appointments",
    module: "Custom-Appointments",
    idField: "Custom-Appointment_id",
    fields: [
      { name: "appointment_date_slot_id", label: "Appointment Date Slot Id" },
      { name: "appointment_time_slot_id", label: "Appointment Time Slot Id" },
      { name: "name", label: "Name" },
      { name: "city", label: "City" },
      { name: "preferred_delivery_date", label: "Preferred Delivery Date", type: "date" },
      { name: "occasion", label: "Occasion" },
      { name: "appointment_status", label: "Appointment Status" },
      { name: "appointment_notes", label: "Appointment Notes", type: "textarea" },
    ],
    listFields: ["appointment_date_slot_id", "appointment_time_slot_id", "name", "city", "preferred_delivery_date"],
  },
  "wishlists": {
    label: "Wishlists",
    module: "Wishlists",
    idField: "Wishlist_id",
    fields: [
      { name: "user_id", label: "User Id" },
      { name: "wishlist_name", label: "Wishlist Name" },
    ],
    listFields: ["user_id", "wishlist_name"],
  },
  "wishlist-items": {
    label: "Wishlist-Items - Wishlist Items",
    module: "Wishlist-Items",
    idField: "Wishlist-Item_id",
    fields: [
      { name: "wishlist_id", label: "Wishlist Id" },
      { name: "product_id", label: "Product Id" },
      { name: "product_variant_id", label: "Product Variant Id" },
    ],
    listFields: ["wishlist_id", "product_id", "product_variant_id"],
  },
  "carts": {
    label: "Carts",
    module: "Carts",
    idField: "Cart_id",
    fields: [
      { name: "user_id", label: "User Id" },
      { name: "cart_status", label: "Cart Status" },
      { name: "total_items", label: "Total Items", type: "number" },
      { name: "total_price", label: "Total Price", type: "number" },
    ],
    listFields: ["user_id", "cart_status", "total_items", "total_price"],
  },
  "cart-items": {
    label: "Cart-Items - Cart Items",
    module: "Cart-Items",
    idField: "Cart-Item_id",
    fields: [
      { name: "cart_id", label: "Cart Id" },
      { name: "product_id", label: "Product Id" },
      { name: "product_variant_id", label: "Product Variant Id" },
      { name: "qty", label: "Qty", type: "number" },
      { name: "unit_price", label: "Unit Price", type: "number" },
    ],
    listFields: ["cart_id", "product_id", "product_variant_id", "qty", "unit_price"],
  },
  "order-items": {
    label: "Order-Items - Order Items",
    module: "Order-Items",
    idField: "Order-Item_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "product_id", label: "Product Id" },
      { name: "product_variant_id", label: "Product Variant Id" },
      { name: "product_name", label: "Product Name" },
      { name: "sku", label: "Sku" },
      { name: "qty", label: "Qty", type: "number" },
      { name: "unit_price", label: "Unit Price", type: "number" },
    ],
    listFields: ["order_id", "product_id", "product_variant_id", "product_name", "sku"],
  },
  "order-addresses": {
    label: "Order-Addresses - Order Addresses",
    module: "Order-Addresses",
    idField: "Order-Addresse_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "address_type", label: "Address Type" },
      { name: "recipient_name", label: "Recipient Name" },
      { name: "phone_number", label: "Phone Number" },
      { name: "address_line1", label: "Address Line1" },
      { name: "address_line2", label: "Address Line2" },
      { name: "city", label: "City" },
      { name: "state", label: "State" },
      { name: "postal_code", label: "Postal Code" },
      { name: "country", label: "Country" },
    ],
    listFields: ["order_id", "address_type", "recipient_name", "phone_number", "address_line1"],
  },
  "order-status-master": {
    label: "Order-Status-Master - Order Status Master",
    module: "Order-Status-Master",
    idField: "Order-Status-Master_id",
    fields: [
      { name: "status_name", label: "Status Name" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "iscancelled_status", label: "Iscancelled Status" },
    ],
    listFields: ["status_name", "display_order", "iscancelled_status"],
  },
  "order-status-history": {
    label: "Order-Status-History - Order Status History",
    module: "Order-Status-History",
    idField: "Order-Status-History_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "oldstatus_id", label: "Oldstatus Id" },
      { name: "newstatus_id", label: "Newstatus Id" },
    ],
    listFields: ["order_id", "oldstatus_id", "newstatus_id"],
  },
  "order-cancellations": {
    label: "Order-Cancellations - Order Cancellations",
    module: "Order-Cancellations",
    idField: "Order-Cancellation_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "cancelled_by", label: "Cancelled By" },
      { name: "cancellation_reason", label: "Cancellation Reason" },
    ],
    listFields: ["order_id", "cancelled_by", "cancellation_reason"],
  },
  "discount-targets": {
    label: "Discount-Targets - Discount Targets",
    module: "Discount-Targets",
    idField: "Discount-Target_id",
    fields: [
      { name: "discount_id", label: "Discount Id" },
      { name: "target_type", label: "Target Type" },
      { name: "target_id", label: "Target Id" },
    ],
    listFields: ["discount_id", "target_type", "target_id"],
  },
  "coupon-usage": {
    label: "Coupon-Usage - Coupon Usage",
    module: "Coupon-Usage",
    idField: "Coupon-Usage_id",
    fields: [
      { name: "coupon_id", label: "Coupon Id" },
      { name: "user_id", label: "User Id" },
      { name: "order_id", label: "Order Id" },
    ],
    listFields: ["coupon_id", "user_id", "order_id"],
  },
  "order-promotions": {
    label: "Order-Promotions - Order Promotions",
    module: "Order-Promotions",
    idField: "Order-Promotion_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "coupon_code", label: "Coupon Code" },
      { name: "discount_name", label: "Discount Name" },
      { name: "discount_type", label: "Discount Type" },
      { name: "discount_value", label: "Discount Value", type: "number" },
    ],
    listFields: ["order_id", "coupon_code", "discount_name", "discount_type", "discount_value"],
  },
  "shipment-events": {
    label: "Shipment-Events - Shipment Events",
    module: "Shipment-Events",
    idField: "Shipment-Event_id",
    fields: [
      { name: "shipment_id", label: "Shipment Id" },
      { name: "event_status", label: "Event Status" },
      { name: "event_location", label: "Event Location" },
    ],
    listFields: ["shipment_id", "event_status", "event_location"],
  },
  "returns": {
    label: "Returns",
    module: "Returns",
    idField: "Return_id",
    fields: [
      { name: "order_item_id", label: "Order Item Id" },
      { name: "return_reason", label: "Return Reason" },
      { name: "return_status", label: "Return Status" },
    ],
    listFields: ["order_item_id", "return_reason", "return_status"],
  },
  "refunds": {
    label: "Refunds",
    module: "Refunds",
    idField: "Refund_id",
    fields: [
      { name: "order_id", label: "Order Id" },
      { name: "refund_amount", label: "Refund Amount", type: "number" },
      { name: "refund_status", label: "Refund Status" },
      { name: "refund_reason", label: "Refund Reason" },
    ],
    listFields: ["order_id", "refund_amount", "refund_status", "refund_reason"],
  },
  "support-contacts": {
    label: "Support-Contacts - Support Contacts",
    module: "Support-Contacts",
    idField: "Support-Contact_id",
    fields: [
      { name: "contact_type", label: "Contact Type" },
      { name: "contact_value", label: "Contact Value" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["contact_type", "contact_value", "display_order"],
  },
  "newsletter-subscriptions": {
    label: "Newsletter-Subscriptions - Newsletter Subscriptions",
    module: "Newsletter-Subscriptions",
    idField: "Newsletter-Subscription_id",
    fields: [
      { name: "emailid", label: "Emailid", type: "email" },
      { name: "subscription_status", label: "Subscription Status" },
    ],
    listFields: ["emailid", "subscription_status"],
  },
  "settings": {
    label: "Settings",
    module: "Settings",
    idField: "Setting_id",
    fields: [
      { name: "setting_key", label: "Setting Key" },
      { name: "setting_value", label: "Setting Value" },
      { name: "brand_description", label: "Brand Description", type: "textarea" },
      { name: "newsletter_description", label: "Newsletter Description", type: "textarea" },
      { name: "isactive", label: "Isactive", type: "checkbox" },
    ],
    listFields: ["setting_key", "setting_value", "brand_description", "newsletter_description", "isactive"],
  },
  "style-collection-media": {
    label: "Style-Collection-Media - Style Collection Media",
    module: "Style-Collection-Media",
    idField: "Style-Collection-Media_id",
    fields: [
      { name: "setting_key", label: "Setting Key" },
      { name: "setting_value", label: "Setting Value" },
      { name: "brand_description", label: "Brand Description", type: "textarea" },
      { name: "newsletter_description", label: "Newsletter Description", type: "textarea" },
      { name: "isactive", label: "Isactive", type: "checkbox" },
    ],
    listFields: ["setting_key", "setting_value", "brand_description", "newsletter_description", "isactive"],
  },
  "style-collections": {
    label: "Style-Collections - Style Collections",
    module: "Style-Collections",
    idField: "Style-Collection_id",
    fields: [
      { name: "setting_key", label: "Setting Key" },
      { name: "setting_value", label: "Setting Value" },
      { name: "brand_description", label: "Brand Description", type: "textarea" },
      { name: "newsletter_description", label: "Newsletter Description", type: "textarea" },
      { name: "isactive", label: "Isactive", type: "checkbox" },
    ],
    listFields: ["setting_key", "setting_value", "brand_description", "newsletter_description", "isactive"],
  },
  "spotlight-media": {
    label: "Spotlight-Media - Spotlight Media",
    module: "Spotlight-Media",
    idField: "Spotlight-Media_id",
    fields: [
      { name: "spotlight_entry_id", label: "Spotlight Entry Id" },
      { name: "media_type", label: "Media Type" },
      { name: "media_url", label: "Media Url", type: "image" },
      { name: "alt_text", label: "Alt Text" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isprimary", label: "Isprimary" },
    ],
    listFields: ["spotlight_entry_id", "media_type", "media_url", "alt_text", "display_order"],
  },
  "spotlight-entries": {
    label: "Spotlight-Entries - Spotlight Entries",
    module: "Spotlight-Entries",
    idField: "Spotlight-Entrie_id",
    fields: [
      { name: "title", label: "Title" },
      { name: "subtitle", label: "Subtitle" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "cta_text", label: "Cta Text" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["title", "subtitle", "description", "redirect_link", "cta_text"],
  },
  "menu-video": {
    label: "Menu-Video - Menu Video",
    module: "Menu-Video",
    idField: "Menu-Video_id",
    fields: [
      { name: "video_type", label: "Video Type" },
      { name: "video_url", label: "Video Url", type: "url" },
      { name: "poster_image_url", label: "Poster Image Url", type: "image" },
      { name: "autoplay", label: "Autoplay" },
      { name: "loop_video", label: "Loop Video" },
      { name: "mute_default", label: "Mute Default" },
      { name: "display_order", label: "Display Order", type: "number" },
    ],
    listFields: ["video_type", "video_url", "poster_image_url", "autoplay", "loop_video"],
  },
  "image-sliders": {
    label: "Image-Sliders - Image Sliders",
    module: "Image-Sliders",
    idField: "Image-Slider_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "f{{p}}-image-sliders": {
    label: "Image-Sliders - F{{P}} Image Sliders",
    module: "F{{P}}/Image-Sliders",
    idField: "f{{P}}_Image-Slider_id",
    fields: [
      { name: "image_url", label: "Image Url", type: "image" },
      { name: "title", label: "Title" },
      { name: "subtitle", label: "Subtitle" },
      { name: "button_text", label: "Button Text" },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "auto_slide_interval_seconds", label: "Auto Slide Interval Seconds", type: "number" },
    ],
    listFields: ["image_url", "title", "subtitle", "button_text", "redirect_link"],
  },
  "legal-page-headers": {
    label: "Legal-Page-Headers - Legal Page Headers",
    module: "Legal-Page-Headers",
    idField: "Legal-Page-Header_id",
    fields: [
      { name: "page_type", label: "Page Type" },
      { name: "page_title", label: "Page Title" },
      { name: "intro_text", label: "Intro Text" },
      { name: "effective_date", label: "Effective Date", type: "date" },
      { name: "version_number", label: "Version Number" },
      { name: "updated_by", label: "Updated By" },
    ],
    listFields: ["page_type", "page_title", "intro_text", "effective_date", "version_number"],
  },
  "legal-page-sections": {
    label: "Legal-Page-Sections - Legal Page Sections",
    module: "Legal-Page-Sections",
    idField: "Legal-Page-Section_id",
    fields: [
      { name: "page_type", label: "Page Type" },
      { name: "section_title", label: "Section Title" },
      { name: "section_order", label: "Section Order", type: "number" },
      { name: "content", label: "Content" },
      { name: "created_by", label: "Created By" },
    ],
    listFields: ["page_type", "section_title", "section_order", "content", "created_by"],
  },
  "variant-rating-summary": {
    label: "Variant Rating Summary",
    module: "Variant-rating-summary",
    idField: "variant-rating-summary_id",
    fields: [
      { name: "variant_id", label: "Variant Id" },
      { name: "avg_rating", label: "Avg Rating", type: "number" },
      { name: "total_reviews", label: "Total Reviews", type: "number" },
    ],
    listFields: ["variant_id", "avg_rating", "total_reviews"],
  },
  "variant-rating-summary-var_001": {
    label: "Variant Rating Summary - Variant Rating Summary Var_001",
    module: "Variant-rating-summary/Var_001",
    idField: "variant-rating-summary_var_001_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "product-rating-summary": {
    label: "Product Rating Summary",
    module: "Product-rating-summary",
    idField: "product-rating-summary_id",
    fields: [
      { name: "product_id", label: "Product Id" },
      { name: "avg_rating", label: "Avg Rating", type: "number" },
      { name: "total_reviews", label: "Total Reviews", type: "number" },
      { name: "rating_5_count", label: "Rating 5 Count", type: "number" },
      { name: "rating_4_count", label: "Rating 4 Count", type: "number" },
      { name: "rating_3_count", label: "Rating 3 Count", type: "number" },
    ],
    listFields: ["product_id", "avg_rating", "total_reviews", "rating_5_count", "rating_4_count"],
  },
  "product-rating-summary-prod_001": {
    label: "Product Rating Summary - Product Rating Summary Prod_001",
    module: "Product-rating-summary/Prod_001",
    idField: "product-rating-summary_prod_001_id",
    fields: [
      { name: "name", label: "Name" },
    ],
    listFields: ["name"],
  },
  "review-votes": {
    label: "Review Votes",
    module: "Review-votes",
    idField: "review-vote_id",
    fields: [
      { name: "review_id", label: "Review Id" },
      { name: "user_id", label: "User Id" },
      { name: "is_helpful", label: "Is Helpful", type: "checkbox" },
    ],
    listFields: ["review_id", "user_id", "is_helpful"],
  },
  "review-media": {
    label: "Review Media",
    module: "Review-media",
    idField: "review-media_id",
    fields: [
      { name: "review_id", label: "Review Id" },
      { name: "media_type", label: "Media Type" },
      { name: "media_url", label: "Media Url", type: "image" },
    ],
    listFields: ["review_id", "media_type", "media_url"],
  },
};

export const generatedNavItems = [
  { path: "/admin/fileupload", label: "Authentication - FileUpload", icon: "⚙️" },
  { path: "/admin/auth-register", label: "Authentication - Auth Register", icon: "⚙️" },
  { path: "/admin/auth-password-login", label: "Authentication - Auth Password Login", icon: "⚙️" },
  { path: "/admin/auth-otp-login", label: "Authentication - Auth OTP Login", icon: "⚙️" },
  { path: "/admin/auth-verify-login-otp", label: "Authentication - Auth Verify Login OTP", icon: "⚙️" },
  { path: "/admin/auth-reset-password", label: "Authentication - Auth Reset Password", icon: "⚙️" },
  { path: "/admin/auth-forgot-password", label: "Authentication - Auth Forgot Password", icon: "⚙️" },
  { path: "/admin/auth-forgot-password-confirm", label: "Authentication - Auth Forgot Password Confirm", icon: "⚙️" },
  { path: "/admin/mail-send-mail", label: "Mail - Mail Send Mail", icon: "⚙️" },
  { path: "/admin/mail-send-otp-email", label: "Mail - Mail Send OTP Email", icon: "⚙️" },
  { path: "/admin/user-roles", label: "User - Roles - User Roles", icon: "⚙️" },
  { path: "/admin/user-roles-user", label: "User - Roles - User Roles User", icon: "⚙️" },
  { path: "/admin/user-roles-add", label: "User - Roles - User Roles Add", icon: "⚙️" },
  { path: "/admin/user-roles-remove", label: "User - Roles - User Roles Remove", icon: "⚙️" },
  { path: "/admin/addresses", label: "Addresses", icon: "⚙️" },
  { path: "/admin/menu-category", label: "Menu Category", icon: "⚙️" },
  { path: "/admin/menu-sub-category", label: "Menu Sub Categories - Menu Sub Category", icon: "⚙️" },
  { path: "/admin/products-media", label: "Products-Media - Products Media", icon: "⚙️" },
  { path: "/admin/products-seo", label: "Products-Seo - Products Seo", icon: "⚙️" },
  { path: "/admin/products-cloth-type-care-instructions", label: "Products-Cloth-Type-Care-Instructions - Products Cloth Type Care Instructions", icon: "⚙️" },
  { path: "/admin/products-care-instructions", label: "Products-Care-Instructions - Products Care Instructions", icon: "⚙️" },
  { path: "/admin/products-cloth-types", label: "Products-Cloth-Types - Products Cloth Types", icon: "⚙️" },
  { path: "/admin/products-sizes", label: "Products-Sizes - Products Sizes", icon: "⚙️" },
  { path: "/admin/products-attributes-values", label: "Products-Attributes-Values - Products Attributes Values", icon: "⚙️" },
  { path: "/admin/products-attributes", label: "Products-Attributes - Products Attributes", icon: "⚙️" },
  { path: "/admin/products-variants", label: "Products-Variants - Products Variants", icon: "⚙️" },
  { path: "/admin/appointment-date-slots", label: "Appointment-Date-Slots - Appointment Date Slots", icon: "⚙️" },
  { path: "/admin/appointment-slot-blocks", label: "Appointment-Slot-Blocks - Appointment Slot Blocks", icon: "⚙️" },
  { path: "/admin/appointment-time-slots", label: "Appointment-Time-Slots - Appointment Time Slots", icon: "⚙️" },
  { path: "/admin/custom-appointments", label: "Custom-Appointments - Custom Appointments", icon: "⚙️" },
  { path: "/admin/wishlists", label: "Wishlists", icon: "⚙️" },
  { path: "/admin/wishlist-items", label: "Wishlist-Items - Wishlist Items", icon: "⚙️" },
  { path: "/admin/carts", label: "Carts", icon: "⚙️" },
  { path: "/admin/cart-items", label: "Cart-Items - Cart Items", icon: "⚙️" },
  { path: "/admin/order-items", label: "Order-Items - Order Items", icon: "⚙️" },
  { path: "/admin/order-addresses", label: "Order-Addresses - Order Addresses", icon: "⚙️" },
  { path: "/admin/order-status-master", label: "Order-Status-Master - Order Status Master", icon: "⚙️" },
  { path: "/admin/order-status-history", label: "Order-Status-History - Order Status History", icon: "⚙️" },
  { path: "/admin/order-cancellations", label: "Order-Cancellations - Order Cancellations", icon: "⚙️" },
  { path: "/admin/discount-targets", label: "Discount-Targets - Discount Targets", icon: "⚙️" },
  { path: "/admin/coupon-usage", label: "Coupon-Usage - Coupon Usage", icon: "⚙️" },
  { path: "/admin/order-promotions", label: "Order-Promotions - Order Promotions", icon: "⚙️" },
  { path: "/admin/shipment-events", label: "Shipment-Events - Shipment Events", icon: "⚙️" },
  { path: "/admin/returns", label: "Returns", icon: "⚙️" },
  { path: "/admin/refunds", label: "Refunds", icon: "⚙️" },
  { path: "/admin/support-contacts", label: "Support-Contacts - Support Contacts", icon: "⚙️" },
  { path: "/admin/newsletter-subscriptions", label: "Newsletter-Subscriptions - Newsletter Subscriptions", icon: "⚙️" },
  { path: "/admin/settings", label: "Settings", icon: "⚙️" },
  { path: "/admin/style-collection-media", label: "Style-Collection-Media - Style Collection Media", icon: "⚙️" },
  { path: "/admin/style-collections", label: "Style-Collections - Style Collections", icon: "⚙️" },
  { path: "/admin/spotlight-media", label: "Spotlight-Media - Spotlight Media", icon: "⚙️" },
  { path: "/admin/spotlight-entries", label: "Spotlight-Entries - Spotlight Entries", icon: "⚙️" },
  { path: "/admin/menu-video", label: "Menu-Video - Menu Video", icon: "⚙️" },
  { path: "/admin/image-sliders", label: "Image-Sliders - Image Sliders", icon: "⚙️" },
  { path: "/admin/f{{p}}-image-sliders", label: "Image-Sliders - F{{P}} Image Sliders", icon: "⚙️" },
  { path: "/admin/legal-page-headers", label: "Legal-Page-Headers - Legal Page Headers", icon: "⚙️" },
  { path: "/admin/legal-page-sections", label: "Legal-Page-Sections - Legal Page Sections", icon: "⚙️" },
  { path: "/admin/variant-rating-summary", label: "Variant Rating Summary", icon: "⚙️" },
  { path: "/admin/variant-rating-summary-var_001", label: "Variant Rating Summary - Variant Rating Summary Var_001", icon: "⚙️" },
  { path: "/admin/product-rating-summary", label: "Product Rating Summary", icon: "⚙️" },
  { path: "/admin/product-rating-summary-prod_001", label: "Product Rating Summary - Product Rating Summary Prod_001", icon: "⚙️" },
  { path: "/admin/review-votes", label: "Review Votes", icon: "⚙️" },
  { path: "/admin/review-media", label: "Review Media", icon: "⚙️" },
];