import {
  FiGrid, FiUsers, FiShield, FiUser, FiBox, FiFolder, FiActivity, FiShoppingBag,
  FiCalendar, FiCreditCard, FiFileText, FiTag, FiDollarSign, FiTruck, FiPackage,
  FiCornerUpLeft, FiHelpCircle, FiPhone, FiBookOpen, FiFilm, FiFeather, FiClock,
  FiSettings, FiMail, FiStar, FiBell, FiRepeat, FiVideo, FiImage,
} from "react-icons/fi";
import api from "../services/api";

const loadProducts = async () => {
  const res = await api.get("/Products");
  const list = res.data?.data || res.data || [];
  return list.map((p) => ({ value: p.product_id, label: p.product_name || p.product_slug || p.product_id }));
};

const loadCategories = async () => {
  const res = await api.get("/Menu-Category");
  const list = res.data?.data || res.data || [];
  return list.map((c) => ({ value: c.menu_category_id, label: c.menu_category_name || c.menu_category_id }));
};

const loadRunningBars = async () => {
  const res = await api.get("/Running-Bar");
  const list = res.data?.data || res.data || [];
  return list.map((r) => ({ value: r.running_bar_id, label: r.running_bar_name || r.running_bar_id }));
};

export const adminNavItems = [
  { path: "/admin", label: "Dashboard", icon: FiGrid },
  { path: "/admin/users", label: "Users", icon: FiUsers },
  { path: "/admin/roles", label: "Roles", icon: FiShield },
  { path: "/admin/profiles", label: "Customer Profiles", icon: FiUser },
  { path: "/admin/products", label: "Products & Media", icon: FiBox },
  { path: "/admin/categories", label: "Categories & Subcategories", icon: FiFolder },
  { path: "/admin/running-bar", label: "Running Bar & Items", icon: FiActivity },
  { path: "/admin/orders", label: "Orders", icon: FiShoppingBag },
  { path: "/admin/appointments", label: "Appointments", icon: FiCalendar },
  { path: "/admin/payments", label: "Payments", icon: FiCreditCard },
  { path: "/admin/invoices", label: "Invoices", icon: FiFileText },
  { path: "/admin/coupons", label: "Coupons", icon: FiTag },
  { path: "/admin/discounts-workspace", label: "Discounts", icon: FiDollarSign },
  { path: "/admin/courier-partners", label: "Courier Partners", icon: FiTruck },
  { path: "/admin/shipments", label: "Shipments", icon: FiPackage },
  { path: "/admin/returns-refunds", label: "Returns & Refunds", icon: FiCornerUpLeft },
  { path: "/admin/faqs", label: "FAQs", icon: FiHelpCircle },
  { path: "/admin/support-contacts", label: "Support Contacts", icon: FiPhone },
  { path: "/admin/legal-pages", label: "Legal Pages", icon: FiBookOpen },
  { path: "/admin/spotlight-media", label: "Spotlight Media", icon: FiFilm },
  { path: "/admin/style-collections-workspace", label: "Style Collections", icon: FiFeather },
  { path: "/admin/appointment-slots", label: "Appointment Availability", icon: FiClock },
  { path: "/admin/refunds", label: "Refunds", icon: FiRepeat },
  { path: "/admin/menu-video", label: "Home Video", icon: FiVideo },
  { path: "/admin/image-sliders", label: "Home Image Sliders", icon: FiImage },
  { path: "/admin/settings", label: "Settings", icon: FiSettings },
  { path: "/admin/newsletters", label: "Newsletters", icon: FiMail },
  { path: "/admin/reviews", label: "Reviews", icon: FiStar },
  { path: "/admin/notifications", label: "Notifications", icon: FiBell },
];

export const moduleConfigs = {
  roles: {
    label: "Roles",
    module: "Roles",
    idField: "role_id",
    fields: [
      { name: "role_name", label: "Role Name", required: true },
      { name: "role_code", label: "Role Code", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["role_name", "role_code", "description", "isactive"],
  },
  users: {
    label: "Users",
    module: "Users",
    idField: "user_id",
    fields: [
      { name: "full_name", label: "Full Name", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone_number", label: "Mobile" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["full_name", "email", "phone_number", "isactive"],
  },
  products: {
    label: "Products",
    module: "Products",
    idField: "product_id",
    fields: [
      { name: "product_name", label: "Product Name", required: true },
      { name: "product_slug", label: "Product Slug" },
      { name: "short_description", label: "Short Description" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "base_price", label: "Price", type: "number" },
      { name: "currency_code", label: "Currency" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["product_name", "product_slug", "base_price", "currency_code", "isactive"],
  },
  categories: {
    label: "Categories",
    module: "Menu-Category",
    idField: "menu_category_id",
    fields: [
      { name: "menu_category_name", label: "Category Name", required: true },
      { name: "menu_category_slug", label: "Slug" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["menu_category_name", "menu_category_slug", "display_order", "isactive"],
  },
  subcategories: {
    label: "Sub Categories",
    module: "Menu-Sub-Category",
    idField: "menu_subcategory_id",
    fields: [
      { name: "menu_subcategory_name", label: "Sub Category Name", required: true },
      { name: "menu_subcategory_slug", label: "Slug" },
      { name: "menu_category_id", label: "Category", type: "select", optionsLoader: loadCategories, required: true },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["menu_subcategory_name", "display_order", "isactive"],
  },
  orders: {
    label: "Orders",
    module: "Orders",
    idField: "order_id",
    fields: [
      { name: "order_number", label: "Order Number" },
      { name: "user_id", label: "User ID" },
      { name: "total_amount", label: "Total Amount", type: "number" },
      { name: "payment_status", label: "Payment Status", type: "select", options: [{ value: "pending", label: "Pending" }, { value: "paid", label: "Paid" }, { value: "failed", label: "Failed" }, { value: "refunded", label: "Refunded" }] },
    ],
    listFields: ["order_number", "total_amount", "payment_status"],
  },
  payments: {
    label: "Payments",
    module: "Payments",
    idField: "payment_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "user_id", label: "User ID" },
      { name: "payment_method_type", label: "Payment Method", type: "select", options: [{ value: "card", label: "Card" }, { value: "upi", label: "UPI" }, { value: "cod", label: "Cash on Delivery" }, { value: "netbanking", label: "Net Banking" }, { value: "wallet", label: "Wallet" }] },
      { name: "amount", label: "Amount", type: "number" },
      { name: "payment_status", label: "Status", type: "select", options: [{ value: "pending", label: "Pending" }, { value: "paid", label: "Paid" }, { value: "failed", label: "Failed" }, { value: "refunded", label: "Refunded" }] },
    ],
    listFields: ["payment_method_type", "amount", "payment_status"],
  },
  notifications: {
    label: "Notifications",
    module: "Notifications",
    idField: "notification_id",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "notification_type", label: "Type" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["title", "notification_type", "isactive"],
  },
  profiles: {
    label: "Customer Profiles",
    module: "Profiles",
    idField: "profile_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "fullname", label: "Full Name" },
      { name: "emailid", label: "Email", type: "email" },
      { name: "mobile_number", label: "Mobile" },
      { name: "dateofbirth", label: "Date of Birth", type: "date" },
      { name: "gender", label: "Gender", type: "select", options: [{ value: "Male", label: "Male" }, { value: "Female", label: "Female" }, { value: "Other", label: "Other" }] },
      { name: "profile_url", label: "Profile Photo URL" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["fullname", "emailid", "gender", "isactive"],
  },
  appointments: {
    label: "Appointments",
    module: "Custom-Appointments",
    idField: "appointment_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "appointment_date_slot_id", label: "Date Slot ID" },
      { name: "appointment_time_slot_id", label: "Time Slot ID" },
      { name: "name", label: "Customer Name" },
      { name: "city", label: "City" },
      { name: "preferred_delivery_date", label: "Preferred Delivery Date", type: "date" },
      { name: "occasion", label: "Occasion" },
      { name: "appointment_status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Confirmed", label: "Confirmed" }, { value: "Completed", label: "Completed" }, { value: "Cancelled", label: "Cancelled" }] },
      { name: "appointment_notes", label: "Notes", type: "textarea" },
    ],
    listFields: ["name", "city", "appointment_status", "preferred_delivery_date"],
  },
  invoices: {
    label: "Invoices",
    module: "Invoices",
    idField: "invoice_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "invoice_number", label: "Invoice Number" },
      { name: "invoice_url", label: "Invoice URL" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["invoice_number", "invoice_url", "isactive"],
  },
  coupons: {
    label: "Coupons",
    module: "Coupons",
    idField: "coupon_id",
    fields: [
      { name: "coupon_code", label: "Coupon Code", required: true },
      { name: "coupon_name", label: "Coupon Name" },
      { name: "description", label: "Description" },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "percent", label: "Percentage" }, { value: "fixed", label: "Fixed" }] },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "min_purchase_amount", label: "Min Purchase Amount", type: "number" },
      { name: "max_discount_amount", label: "Max Discount Amount", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["coupon_code", "coupon_name", "discount_value", "discount_type", "end_date", "isactive"],
  },
  discounts: {
    label: "Discounts",
    module: "Discounts",
    idField: "discount_id",
    fields: [
      { name: "discount_name", label: "Discount Name", required: true },
      { name: "description", label: "Description" },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "percent", label: "Percentage" }, { value: "fixed", label: "Fixed" }] },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "max_discount_amount", label: "Max Discount Amount", type: "number" },
      { name: "usage_limit", label: "Usage Limit", type: "number" },
      { name: "discount_priority", label: "Priority", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["discount_name", "discount_value", "discount_type", "isactive"],
  },
  "courier-partners": {
    label: "Courier Partners",
    module: "Courier-Partners",
    idField: "courier_partner_id",
    fields: [
      { name: "courier_name", label: "Courier Name", required: true },
      { name: "courier_code", label: "Courier Code", required: true },
      { name: "contact_email", label: "Contact Email", type: "email" },
      { name: "contact_phone", label: "Contact Phone" },
      { name: "base_rate", label: "Base Rate", type: "number" },
      { name: "rate_per_kg", label: "Rate Per Kg", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["courier_name", "courier_code", "contact_email", "contact_phone", "isactive"],
  },
  shipments: {
    label: "Shipments",
    module: "Shipments",
    idField: "shipment_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "courier_partner_id", label: "Courier Partner ID" },
      { name: "tracking_number", label: "Tracking Number" },
      { name: "shipment_status", label: "Status", type: "select", options: [{ value: "created", label: "Created" }, { value: "in_transit", label: "In Transit" }, { value: "out_for_delivery", label: "Out for Delivery" }, { value: "delivered", label: "Delivered" }, { value: "returned", label: "Returned" }] },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["tracking_number", "shipment_status", "isactive"],
  },
  "returns-refunds": {
    label: "Returns & Refunds",
    module: "Returns",
    idField: "return_id",
    fields: [
      { name: "order_id", label: "Order ID", required: true },
      { name: "user_id", label: "User ID", required: true },
      { name: "return_type", label: "Return Type", required: true },
      { name: "return_reason", label: "Reason", type: "textarea" },
      { name: "return_status", label: "Status", type: "select", options: [{ value: "requested", label: "Requested" }, { value: "approved", label: "Approved" }, { value: "rejected", label: "Rejected" }, { value: "completed", label: "Completed" }] },
      { name: "return_amount", label: "Return Amount", type: "number" },
      { name: "rma_number", label: "RMA Number" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["return_type", "return_reason", "return_status", "isactive"],
  },
  faqs: {
    label: "FAQs",
    module: "FAQs",
    idField: "faq_id",
    fields: [
      { name: "question", label: "Question", type: "textarea", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["question", "display_order", "isactive"],
  },
  newsletters: {
    label: "Newsletters",
    module: "Newsletter-Subscriptions",
    idField: "newsletter_subscription_id",
    fields: [
      { name: "emailid", label: "Email", type: "email", required: true },
      { name: "subscription_status", label: "Status", type: "select", options: [{ value: "subscribed", label: "Subscribed" }, { value: "unsubscribed", label: "Unsubscribed" }] },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["emailid", "subscription_status", "isactive"],
  },
  reviews: {
    label: "Reviews",
    module: "Reviews",
    idField: "review_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "product_id", label: "Product ID" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "review_text", label: "Review", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["rating", "review_text", "isactive"],
  },
  "running-bar": {
    label: "Running Bar",
    module: "Running-Bar",
    idField: "running_bar_id",
    fields: [
      { name: "running_bar_name", label: "Running Bar Name", required: true },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["running_bar_name", "isactive"],
  },
  "running-bar-items": {
    label: "Running Bar Items",
    module: "Running-Bar-Items",
    idField: "running_bar_item_id",
    fields: [
      { name: "running_bar_id", label: "Running Bar", type: "select", optionsLoader: loadRunningBars, required: true },
      { name: "itemsdata", label: "Item Text", required: true },
      { name: "duration_seconds", label: "Duration (seconds)", type: "number" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["itemsdata", "duration_seconds", "display_order", "isactive"],
  },
  "product-media": {
    label: "Product Media",
    module: "Products-Media",
    idField: "product_media_id",
    fields: [
      { name: "product_id", label: "Product", type: "select", optionsLoader: loadProducts, required: true },
      { name: "media_type", label: "Media Type", type: "select", options: [{ value: "image", label: "Image" }, { value: "video", label: "Video" }] },
      { name: "media_url", label: "Media URL", type: "image", required: true },
      { name: "alt_text", label: "Alt Text" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isprimary", label: "Primary", type: "checkbox" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["media_type", "alt_text", "display_order", "isprimary", "isactive"],
  },
  "product-sizes": {
    label: "Product Sizes",
    module: "Products-Sizes",
    idField: "size_id",
    fields: [
      { name: "size_name", label: "Size Name", required: true },
      { name: "size_type", label: "Size Type", type: "select", options: [{ value: "alpha", label: "Alpha (S/M/L)" }, { value: "numeric", label: "Numeric (28/30/32)" }] },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["size_name", "size_type", "display_order", "isactive"],
  },
  "product-cloth-types": {
    label: "Cloth Types",
    module: "Products-Cloth-Types",
    idField: "cloth_type_id",
    fields: [
      { name: "cloth_type_name", label: "Cloth Type Name", required: true },
      { name: "cloth_type_slug", label: "Slug" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["cloth_type_name", "cloth_type_slug", "display_order", "isactive"],
  },
  "product-care": {
    label: "Care Instructions",
    module: "Products-Care-Instructions",
    idField: "care_instruction_id",
    fields: [
      { name: "instruction_text", label: "Instruction Text", type: "textarea", required: true },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["instruction_text", "display_order", "isactive"],
  },
  "product-seo": {
    label: "Product SEO",
    module: "Products-Seo",
    idField: "product_seo_id",
    fields: [
      { name: "product_id", label: "Product", type: "select", optionsLoader: loadProducts, required: true },
      { name: "seo_title", label: "SEO Title", required: true },
      { name: "seo_description", label: "SEO Description", type: "textarea" },
      { name: "seo_keywords", label: "SEO Keywords" },
      { name: "og_image_url", label: "OG Image URL", type: "image" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["seo_title", "seo_keywords", "isactive"],
  },
  refunds: {
    label: "Refunds",
    module: "Refunds",
    idField: "refund_id",
    fields: [
      { name: "order_id", label: "Order ID", required: true },
      { name: "return_id", label: "Return ID" },
      { name: "payment_id", label: "Payment ID" },
      { name: "user_id", label: "User ID", required: true },
      { name: "refund_type", label: "Refund Type" },
      { name: "refund_amount", label: "Refund Amount", type: "number", required: true },
      { name: "refund_status", label: "Status", type: "select", options: [{ value: "initiated", label: "Initiated" }, { value: "processing", label: "Processing" }, { value: "success", label: "Success" }, { value: "failed", label: "Failed" }] },
      { name: "refund_method", label: "Refund Method" },
      { name: "transaction_id", label: "Transaction ID" },
    ],
    listFields: ["refund_type", "refund_amount", "refund_status"],
  },
  "menu-video": {
    label: "Home Video",
    module: "Menu-Video",
    idField: "menu_video_id",
    fields: [
      { name: "video_type", label: "Video Type", type: "select", options: [{ value: "youtube", label: "YouTube" }, { value: "upload", label: "Uploaded File" }] },
      { name: "video_url", label: "Video URL", required: true },
      { name: "poster_image_url", label: "Poster Image URL", type: "image" },
      { name: "autoplay", label: "Autoplay", type: "checkbox" },
      { name: "loop_video", label: "Loop", type: "checkbox" },
      { name: "mute_default", label: "Muted by Default", type: "checkbox" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["video_type", "video_url", "display_order", "isactive"],
  },
  "image-sliders": {
    label: "Home Image Sliders",
    module: "Image-Sliders",
    idField: "image_slider_id",
    fields: [
      { name: "image_url", label: "Image URL", type: "image", required: true },
      { name: "title", label: "Title" },
      { name: "subtitle", label: "Subtitle" },
      { name: "button_text", label: "Button Text" },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "auto_slide_interval_seconds", label: "Auto Slide Interval (sec)", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox", defaultValue: true },
    ],
    listFields: ["title", "image_url", "display_order", "isactive"],
  },
};
