export const adminNavItems = [
  { path: "/admin", label: "Dashboard", icon: "📊" },
  { path: "/admin/roles", label: "Roles", icon: "🛡️" },
  { path: "/admin/users", label: "Users", icon: "👤" },
  { path: "/admin/products", label: "Products", icon: "🧥" },
  { path: "/admin/categories", label: "Categories", icon: "📁" },
  { path: "/admin/subcategories", label: "Sub Categories", icon: "📂" },
  { path: "/admin/orders", label: "Orders", icon: "📦" },
  { path: "/admin/payments", label: "Payments", icon: "💳" },
  { path: "/admin/notifications", label: "Notifications", icon: "🔔" },
  { path: "/admin/profiles", label: "Customer Profiles", icon: "👥" },
  { path: "/admin/appointments", label: "Appointments", icon: "📅" },
  { path: "/admin/invoices", label: "Invoices", icon: "🧾" },
  { path: "/admin/coupons", label: "Coupons", icon: "🏷️" },
  { path: "/admin/discounts", label: "Discounts", icon: "💰" },
  { path: "/admin/campaigns", label: "Campaigns", icon: "📢" },
  { path: "/admin/courier-partners", label: "Courier Partners", icon: "🚚" },
  { path: "/admin/shipments", label: "Shipments", icon: "🚛" },
  { path: "/admin/returns-refunds", label: "Returns & Refunds", icon: "↩️" },
  { path: "/admin/faqs", label: "FAQs", icon: "❓" },
  { path: "/admin/newsletters", label: "Newsletters", icon: "📰" },
  { path: "/admin/reviews", label: "Reviews", icon: "⭐" },
];

export const moduleConfigs = {
  roles: {
    label: "Roles",
    module: "Roles",
    fields: [
      { name: "role_name", label: "Role Name", required: true },
      { name: "role_description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["role_name", "role_description", "is_active"],
  },
  users: {
    label: "Users",
    module: "Users",
    fields: [
      { name: "full_name", label: "Full Name", required: true },
      { name: "email_id", label: "Email", type: "email", required: true },
      { name: "mobile_number", label: "Mobile" },
      { name: "password", label: "Password", type: "password" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["full_name", "email_id", "mobile_number", "is_active"],
  },
  products: {
    label: "Products",
    module: "Products",
    fields: [
      { name: "product_name", label: "Product Name", required: true },
      { name: "product_code", label: "Product Code" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "price", label: "Price", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["product_name", "product_code", "price", "is_active"],
  },
  categories: {
    label: "Categories",
    module: "Menu-Category",
    fields: [
      { name: "category_name", label: "Category Name", required: true },
      { name: "category_description", label: "Description", type: "textarea" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["category_name", "category_description", "display_order", "is_active"],
  },
  subcategories: {
    label: "Sub Categories",
    module: "Menu-Sub-Category",
    fields: [
      { name: "sub_category_name", label: "Sub Category Name", required: true },
      { name: "menu_category_id", label: "Category ID", type: "number" },
      { name: "sub_category_description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["sub_category_name", "menu_category_id", "is_active"],
  },
  orders: {
    label: "Orders",
    module: "Orders",
    fields: [
      { name: "order_number", label: "Order Number" },
      { name: "user_id", label: "User ID", type: "number" },
      { name: "total_amount", label: "Total Amount", type: "number" },
      { name: "order_status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Processing", label: "Processing" }, { value: "Shipped", label: "Shipped" }, { value: "Delivered", label: "Delivered" }, { value: "Cancelled", label: "Cancelled" }] },
    ],
    listFields: ["order_number", "user_id", "total_amount", "order_status"],
  },
  payments: {
    label: "Payments",
    module: "Payments",
    fields: [
      { name: "order_id", label: "Order ID", type: "number" },
      { name: "payment_method", label: "Payment Method" },
      { name: "payment_amount", label: "Amount", type: "number" },
      { name: "payment_status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Completed", label: "Completed" }, { value: "Failed", label: "Failed" }, { value: "Refunded", label: "Refunded" }] },
    ],
    listFields: ["order_id", "payment_method", "payment_amount", "payment_status"],
  },
  notifications: {
    label: "Notifications",
    module: "Notifications",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "notification_type", label: "Type" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["title", "notification_type", "is_active"],
  },
  profiles: {
    label: "Customer Profiles",
    module: "Profiles",
    fields: [
      { name: "user_id", label: "User ID", type: "number" },
      { name: "full_name", label: "Full Name" },
      { name: "date_of_birth", label: "Date of Birth", type: "date" },
      { name: "gender", label: "Gender", type: "select", options: [{ value: "Male", label: "Male" }, { value: "Female", label: "Female" }, { value: "Other", label: "Other" }] },
    ],
    listFields: ["user_id", "full_name", "gender"],
  },
  appointments: {
    label: "Appointments",
    module: "Custom-Appointments",
    fields: [
      { name: "user_id", label: "User ID", type: "number" },
      { name: "appointment_date", label: "Date", type: "date" },
      { name: "appointment_time", label: "Time" },
      { name: "status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Confirmed", label: "Confirmed" }, { value: "Completed", label: "Completed" }, { value: "Cancelled", label: "Cancelled" }] },
    ],
    listFields: ["user_id", "appointment_date", "appointment_time", "status"],
  },
  invoices: {
    label: "Invoices",
    module: "Invoices",
    fields: [
      { name: "order_id", label: "Order ID", type: "number" },
      { name: "invoice_number", label: "Invoice Number" },
      { name: "invoice_amount", label: "Amount", type: "number" },
      { name: "invoice_date", label: "Date", type: "date" },
    ],
    listFields: ["invoice_number", "order_id", "invoice_amount", "invoice_date"],
  },
  coupons: {
    label: "Coupons",
    module: "Coupons",
    fields: [
      { name: "coupon_code", label: "Coupon Code", required: true },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "Percentage", label: "Percentage" }, { value: "Fixed", label: "Fixed" }] },
      { name: "valid_from", label: "Valid From", type: "date" },
      { name: "valid_until", label: "Valid Until", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["coupon_code", "discount_value", "discount_type", "is_active"],
  },
  discounts: {
    label: "Discounts",
    module: "Discounts",
    fields: [
      { name: "discount_name", label: "Discount Name", required: true },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "Percentage", label: "Percentage" }, { value: "Fixed", label: "Fixed" }] },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["discount_name", "discount_value", "discount_type", "is_active"],
  },
  campaigns: {
    label: "Campaigns",
    module: "Spotlight-Entries",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "subtitle", label: "Subtitle" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["title", "start_date", "end_date", "is_active"],
  },
  "courier-partners": {
    label: "Courier Partners",
    module: "Courier-Partners",
    fields: [
      { name: "partner_name", label: "Partner Name", required: true },
      { name: "contact_email", label: "Contact Email", type: "email" },
      { name: "contact_phone", label: "Contact Phone" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["partner_name", "contact_email", "contact_phone", "is_active"],
  },
  shipments: {
    label: "Shipments",
    module: "Shipments",
    fields: [
      { name: "order_id", label: "Order ID", type: "number" },
      { name: "courier_partner_id", label: "Courier Partner ID", type: "number" },
      { name: "tracking_number", label: "Tracking Number" },
      { name: "shipment_status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "In Transit", label: "In Transit" }, { value: "Delivered", label: "Delivered" }] },
    ],
    listFields: ["order_id", "tracking_number", "shipment_status"],
  },
  "returns-refunds": {
    label: "Returns & Refunds",
    module: "Returns",
    fields: [
      { name: "order_id", label: "Order ID", type: "number" },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Approved", label: "Approved" }, { value: "Rejected", label: "Rejected" }, { value: "Completed", label: "Completed" }] },
    ],
    listFields: ["order_id", "reason", "status"],
  },
  faqs: {
    label: "FAQs",
    module: "FAQs",
    fields: [
      { name: "question", label: "Question", type: "textarea", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    listFields: ["question", "display_order", "is_active"],
  },
  newsletters: {
    label: "Newsletters",
    module: "Newsletter-Subscriptions",
    fields: [
      { name: "email_id", label: "Email", type: "email", required: true },
      { name: "is_subscribed", label: "Subscribed", type: "checkbox" },
    ],
    listFields: ["email_id", "is_subscribed"],
  },
  reviews: {
    label: "Reviews",
    module: "Reviews",
    fields: [
      { name: "user_id", label: "User ID", type: "number" },
      { name: "product_id", label: "Product ID", type: "number" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "review_text", label: "Review", type: "textarea" },
      { name: "is_approved", label: "Approved", type: "checkbox" },
    ],
    listFields: ["user_id", "product_id", "rating", "is_approved"],
  },
};
