import api from "../services/api";

const loadProducts = async () => {
  const res = await api.get("/Products");
  const list = res.data?.data || res.data || [];
  return list.map((p) => ({ value: p.product_id, label: p.product_name || p.product_slug || p.product_id }));
};

const loadCategories = async () => {
  const res = await api.get("/Menu-Category");
  const list = res.data?.data || res.data || [];
  return list.map((c) => ({ value: c.menu_category_id, label: c.menu_category_name || c.menu_category_id }));
};

const loadRunningBars = async () => {
  const res = await api.get("/Running-Bar");
  const list = res.data?.data || res.data || [];
  return list.map((r) => ({ value: r.running_bar_id, label: r.running_bar_name || r.running_bar_id }));
};

export const adminNavItems = [
  { path: "/admin", label: "Dashboard", icon: "📊" },
  { path: "/admin/users", label: "Users", icon: "�" },
  { path: "/admin/roles", label: "Roles", icon: "�️" },
  { path: "/admin/profiles", label: "Customer Profiles", icon: "👥" },
  { path: "/admin/products", label: "Products & Media", icon: "�" },
  { path: "/admin/categories", label: "Categories", icon: "🗂️" },
  { path: "/admin/subcategories", label: "Sub Categories", icon: "📂" },
  { path: "/admin/running-bar", label: "Running Bar", icon: "📣" },
  { path: "/admin/running-bar-items", label: "Running Bar Items", icon: "📝" },
  { path: "/admin/orders", label: "Orders", icon: "📦" },
  { path: "/admin/appointments", label: "Appointments", icon: "📅" },
  { path: "/admin/payments", label: "Payments", icon: "💳" },
  { path: "/admin/invoices", label: "Invoices", icon: "🧾" },
  { path: "/admin/coupons", label: "Coupons", icon: "🏷️" },
  { path: "/admin/discounts", label: "Discounts", icon: "💰" },
  { path: "/admin/campaigns", label: "Campaigns", icon: "📢" },
  { path: "/admin/courier-partners", label: "Courier Partners", icon: "🚚" },
  { path: "/admin/shipments", label: "Shipments", icon: "🚛" },
  { path: "/admin/returns-refunds", label: "Returns & Refunds", icon: "↩️" },
  { path: "/admin/faqs", label: "FAQs", icon: "❓" },
  { path: "/admin/support-contacts", label: "Support Contacts", icon: "📞" },
  { path: "/admin/legal-pages", label: "Legal Pages", icon: "📜" },
  { path: "/admin/spotlight-media", label: "Spotlight Media", icon: "🎥" },
  { path: "/admin/settings", label: "Settings", icon: "⚙️" },
  { path: "/admin/newsletters", label: "Newsletters", icon: "📰" },
  { path: "/admin/reviews", label: "Reviews", icon: "⭐" },
  { path: "/admin/notifications", label: "Notifications", icon: "🔔" },
];

export const moduleConfigs = {
  roles: {
    label: "Roles",
    module: "Roles",
    idField: "role_id",
    fields: [
      { name: "role_name", label: "Role Name", required: true },
      { name: "role_code", label: "Role Code", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["role_name", "role_code", "description", "isactive"],
  },
  users: {
    label: "Users",
    module: "Users",
    idField: "user_id",
    fields: [
      { name: "full_name", label: "Full Name", required: true },
      { name: "email_id", label: "Email", type: "email", required: true },
      { name: "mobile_number", label: "Mobile" },
      { name: "password", label: "Password", type: "password" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["full_name", "email_id", "mobile_number", "isactive"],
  },
  products: {
    label: "Products",
    module: "Products",
    idField: "product_id",
    fields: [
      { name: "product_name", label: "Product Name", required: true },
      { name: "product_slug", label: "Product Slug" },
      { name: "short_description", label: "Short Description" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "base_price", label: "Price", type: "number" },
      { name: "currency_code", label: "Currency" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["product_name", "product_slug", "base_price", "currency_code", "isactive"],
  },
  categories: {
    label: "Categories",
    module: "Menu-Category",
    idField: "menu_category_id",
    fields: [
      { name: "menu_category_name", label: "Category Name", required: true },
      { name: "menu_category_slug", label: "Slug" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["menu_category_name", "menu_category_slug", "display_order", "isactive"],
  },
  subcategories: {
    label: "Sub Categories",
    module: "Menu-Sub-Category",
    idField: "menu_subcategory_id",
    fields: [
      { name: "menu_subcategory_name", label: "Sub Category Name", required: true },
      { name: "menu_subcategory_slug", label: "Slug" },
      { name: "menu_category_id", label: "Category", type: "select", optionsLoader: loadCategories, required: true },
      { name: "redirect_link", label: "Redirect Link" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["menu_subcategory_name", "menu_category_id", "display_order", "isactive"],
  },
  orders: {
    label: "Orders",
    module: "Orders",
    idField: "order_id",
    fields: [
      { name: "order_number", label: "Order Number" },
      { name: "user_id", label: "User ID" },
      { name: "total_price", label: "Total Amount", type: "number" },
      { name: "payment_status", label: "Payment Status", type: "select", options: [{ value: "pending", label: "Pending" }, { value: "completed", label: "Completed" }, { value: "failed", label: "Failed" }, { value: "refunded", label: "Refunded" }] },
    ],
    listFields: ["order_number", "user_id", "total_price", "payment_status"],
  },
  payments: {
    label: "Payments",
    module: "Payments",
    idField: "payment_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "user_id", label: "User ID" },
      { name: "payment_method", label: "Payment Method", type: "select", options: [{ value: "card", label: "Card" }, { value: "upi", label: "UPI" }, { value: "cod", label: "Cash on Delivery" }, { value: "netbanking", label: "Net Banking" }] },
      { name: "amount", label: "Amount", type: "number" },
      { name: "payment_status", label: "Status", type: "select", options: [{ value: "pending", label: "Pending" }, { value: "completed", label: "Completed" }, { value: "failed", label: "Failed" }, { value: "refunded", label: "Refunded" }] },
    ],
    listFields: ["order_id", "payment_method", "amount", "payment_status"],
  },
  notifications: {
    label: "Notifications",
    module: "Notifications",
    idField: "notification_id",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "notification_type", label: "Type" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["title", "notification_type", "isactive"],
  },
  profiles: {
    label: "Customer Profiles",
    module: "Profiles",
    idField: "profile_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "fullname", label: "Full Name" },
      { name: "emailid", label: "Email", type: "email" },
      { name: "mobile_number", label: "Mobile" },
      { name: "dateofbirth", label: "Date of Birth", type: "date" },
      { name: "gender", label: "Gender", type: "select", options: [{ value: "Male", label: "Male" }, { value: "Female", label: "Female" }, { value: "Other", label: "Other" }] },
      { name: "profile_url", label: "Profile Photo URL" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["user_id", "fullname", "emailid", "gender", "isactive"],
  },
  appointments: {
    label: "Appointments",
    module: "Custom-Appointments",
    idField: "appointment_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "appointment_date_slot_id", label: "Date Slot ID" },
      { name: "appointment_time_slot_id", label: "Time Slot ID" },
      { name: "name", label: "Customer Name" },
      { name: "city", label: "City" },
      { name: "preferred_delivery_date", label: "Preferred Delivery Date", type: "date" },
      { name: "occasion", label: "Occasion" },
      { name: "appointment_status", label: "Status", type: "select", options: [{ value: "Pending", label: "Pending" }, { value: "Confirmed", label: "Confirmed" }, { value: "Completed", label: "Completed" }, { value: "Cancelled", label: "Cancelled" }] },
      { name: "appointment_notes", label: "Notes", type: "textarea" },
    ],
    listFields: ["name", "city", "appointment_status", "preferred_delivery_date"],
  },
  invoices: {
    label: "Invoices",
    module: "Invoices",
    idField: "invoice_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "invoice_number", label: "Invoice Number" },
      { name: "invoice_amount", label: "Amount", type: "number" },
      { name: "invoice_date", label: "Date", type: "date" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["invoice_number", "order_id", "invoice_amount", "invoice_date", "isactive"],
  },
  coupons: {
    label: "Coupons",
    module: "Coupons",
    idField: "coupon_id",
    fields: [
      { name: "coupon_code", label: "Coupon Code", required: true },
      { name: "description", label: "Description" },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "percent", label: "Percentage" }, { value: "fixed", label: "Fixed" }] },
      { name: "valid_from", label: "Valid From", type: "date" },
      { name: "valid_till", label: "Valid Until", type: "date" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["coupon_code", "discount_value", "discount_type", "valid_till", "isactive"],
  },
  discounts: {
    label: "Discounts",
    module: "Discounts",
    idField: "discount_id",
    fields: [
      { name: "discount_name", label: "Discount Name", required: true },
      { name: "discount_value", label: "Discount Value", type: "number" },
      { name: "discount_type", label: "Discount Type", type: "select", options: [{ value: "percent", label: "Percentage" }, { value: "fixed", label: "Fixed" }] },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["discount_name", "discount_value", "discount_type", "isactive"],
  },
  campaigns: {
    label: "Campaigns",
    module: "Spotlight-Entries",
    idField: "spotlight_entry_id",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "subtitle", label: "Subtitle" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["title", "start_date", "end_date", "isactive"],
  },
  "courier-partners": {
    label: "Courier Partners",
    module: "Courier-Partners",
    idField: "courier_partner_id",
    fields: [
      { name: "partner_name", label: "Partner Name", required: true },
      { name: "contact_email", label: "Contact Email", type: "email" },
      { name: "contact_phone", label: "Contact Phone" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["partner_name", "contact_email", "contact_phone", "isactive"],
  },
  shipments: {
    label: "Shipments",
    module: "Shipments",
    idField: "shipment_id",
    fields: [
      { name: "order_id", label: "Order ID" },
      { name: "courier_partner_id", label: "Courier Partner ID" },
      { name: "tracking_number", label: "Tracking Number" },
      { name: "shipment_status", label: "Status", type: "select", options: [{ value: "created", label: "Created" }, { value: "in_transit", label: "In Transit" }, { value: "out_for_delivery", label: "Out for Delivery" }, { value: "delivered", label: "Delivered" }, { value: "returned", label: "Returned" }] },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["order_id", "tracking_number", "shipment_status", "isactive"],
  },
  "returns-refunds": {
    label: "Returns & Refunds",
    module: "Returns",
    idField: "return_id",
    fields: [
      { name: "order_item_id", label: "Order Item ID" },
      { name: "return_reason", label: "Reason", type: "textarea" },
      { name: "return_status", label: "Status", type: "select", options: [{ value: "requested", label: "Requested" }, { value: "approved", label: "Approved" }, { value: "rejected", label: "Rejected" }, { value: "completed", label: "Completed" }] },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["order_item_id", "return_reason", "return_status", "isactive"],
  },
  faqs: {
    label: "FAQs",
    module: "FAQs",
    idField: "faq_id",
    fields: [
      { name: "question", label: "Question", type: "textarea", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["question", "display_order", "isactive"],
  },
  newsletters: {
    label: "Newsletters",
    module: "Newsletter-Subscriptions",
    idField: "newsletter_subscription_id",
    fields: [
      { name: "emailid", label: "Email", type: "email", required: true },
      { name: "subscription_status", label: "Status", type: "select", options: [{ value: "subscribed", label: "Subscribed" }, { value: "unsubscribed", label: "Unsubscribed" }] },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["emailid", "subscription_status", "isactive"],
  },
  reviews: {
    label: "Reviews",
    module: "Reviews",
    idField: "review_id",
    fields: [
      { name: "user_id", label: "User ID" },
      { name: "product_id", label: "Product ID" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "review_text", label: "Review", type: "textarea" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["user_id", "product_id", "rating", "isactive"],
  },
  "running-bar": {
    label: "Running Bar",
    module: "Running-Bar",
    idField: "running_bar_id",
    fields: [
      { name: "running_bar_name", label: "Running Bar Name", required: true },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["running_bar_name", "isactive"],
  },
  "running-bar-items": {
    label: "Running Bar Items",
    module: "Running-Bar-Items",
    idField: "running_bar_item_id",
    fields: [
      { name: "running_bar_id", label: "Running Bar", type: "select", optionsLoader: loadRunningBars, required: true },
      { name: "itemsdata", label: "Item Text", required: true },
      { name: "duration_seconds", label: "Duration (seconds)", type: "number" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["itemsdata", "running_bar_id", "duration_seconds", "display_order", "isactive"],
  },
  "product-media": {
    label: "Product Media",
    module: "Products-Media",
    idField: "product_media_id",
    fields: [
      { name: "product_id", label: "Product", type: "select", optionsLoader: loadProducts, required: true },
      { name: "media_type", label: "Media Type", type: "select", options: [{ value: "image", label: "Image" }, { value: "video", label: "Video" }] },
      { name: "media_url", label: "Media URL", type: "image", required: true },
      { name: "alt_text", label: "Alt Text" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isprimary", label: "Primary", type: "checkbox" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["product_id", "media_type", "alt_text", "display_order", "isprimary", "isactive"],
  },
  "product-sizes": {
    label: "Product Sizes",
    module: "Products-Sizes",
    idField: "size_id",
    fields: [
      { name: "size_name", label: "Size Name", required: true },
      { name: "size_type", label: "Size Type", type: "select", options: [{ value: "alpha", label: "Alpha (S/M/L)" }, { value: "numeric", label: "Numeric (28/30/32)" }] },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["size_name", "size_type", "display_order", "isactive"],
  },
  "product-cloth-types": {
    label: "Cloth Types",
    module: "Products-Cloth-Types",
    idField: "cloth_type_id",
    fields: [
      { name: "cloth_type_name", label: "Cloth Type Name", required: true },
      { name: "cloth_type_slug", label: "Slug" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["cloth_type_name", "cloth_type_slug", "display_order", "isactive"],
  },
  "product-care": {
    label: "Care Instructions",
    module: "Products-Care-Instructions",
    idField: "care_instruction_id",
    fields: [
      { name: "instruction_text", label: "Instruction Text", type: "textarea", required: true },
      { name: "display_order", label: "Display Order", type: "number" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["instruction_text", "display_order", "isactive"],
  },
  "product-seo": {
    label: "Product SEO",
    module: "Products-Seo",
    idField: "product_seo_id",
    fields: [
      { name: "product_id", label: "Product", type: "select", optionsLoader: loadProducts, required: true },
      { name: "seo_title", label: "SEO Title", required: true },
      { name: "seo_description", label: "SEO Description", type: "textarea" },
      { name: "seo_keywords", label: "SEO Keywords" },
      { name: "og_image_url", label: "OG Image URL", type: "image" },
      { name: "isactive", label: "Active", type: "checkbox" },
    ],
    listFields: ["product_id", "seo_title", "seo_keywords", "isactive"],
  },
};
